/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs41acl.h"

bool_t
xdr_acetype4 (XDR *xdrs, acetype4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_aceflag4 (XDR *xdrs, aceflag4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_aceiflag4 (XDR *xdrs, aceiflag4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_acemask4 (XDR *xdrs, acemask4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nfsace4i (XDR *xdrs, nfsace4i *objp)
{
	register int32_t *buf;

	 if (!xdr_acetype4 (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_aceflag4 (xdrs, &objp->flag))
		 return FALSE;
	 if (!xdr_aceiflag4 (xdrs, &objp->iflag))
		 return FALSE;
	 if (!xdr_acemask4 (xdrs, &objp->access_mask))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->who))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_aclflag4 (XDR *xdrs, aclflag4 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nfsacl41i (XDR *xdrs, nfsacl41i *objp)
{
	register int32_t *buf;

	 if (!xdr_aclflag4 (xdrs, &objp->na41_flag))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->na41_aces.na41_aces_val, (u_int *) &objp->na41_aces.na41_aces_len, ~0,
		sizeof (nfsace4i), (xdrproc_t) xdr_nfsace4i))
		 return FALSE;
	return TRUE;
}
